### ISSUE TITLE
2 Bugs !!!!!

### ISSUE THREAD

**Issue by HamzaMihfad** [3imed-jaberi/any-to-any#17]
------------ Bug 1 ------------
convert(0, 10, 36) returns null, it should be 0

------------ Bug 2 ------------
change:
const { Convert } = require('any-to-any')
to:
const { convert } = require('any-to-any')

**Comment by 3imed-jaberi** [comment]
Thank you @HamzaMihfad for your report.

For the 1st bug, yes it exists but doesn't return `null` it returns an empty string `''` because of [this line](https://github.com/3imed-jaberi/any-to-any/blob/master/index.ts#L14) when I init. the result variable with an empty string.
Don't worry I will fix that. Also, I will make the module work faster with 0 values as you know 0 from x base to y base is always equal to 0.

For the 2nd bug, It's not a bug. It's just a typo in the documentation (`README.md`) 😅.

**Comment by 3imed-jaberi** [comment]
@HamzaMihfad, I found some npm error to publish the new version (problem-related to npm). soon I will publish the current version. For now, you can install directly from GitHub by running this command;
```shell
npm i https://github.com/3imed-jaberi/any-to-any
```

**Comment by HamzaMihfad** [comment]
@3imed-jaberi thank you so much!

**Comment by 3imed-jaberi** [comment]
@HamzaMihfad, I publish it now to npm registry so you can use the old behave.
```bash
npm i any-to-any
```
